#!/usr/bin/env python3
"""Generate catalog/known_sites.tsv: a flat, read-only dedupe snapshot derived from the
canonical catalog (reports/*/meta.json + each report's backtrace.txt). Fuzzer instances
and the ingest tool load this instead of parsing every meta.json; it is regenerated by
the single writer (triage) whenever the catalog changes -- so there is never a shared
*mutable* catalog and thus no concurrent-write problem.

Row format (tab-separated):  <oom_id>\t<kind>\t<keytype>\t<key>
  keytype=func   key=<file>:<func>          (most stable across line drift)
  keytype=line   key=<file>:<line>          (exact; near-match handled by the matcher)
  keytype=assert key=<assertion expression> (discriminates same-func eval asserts)
  keytype=msg    key=<fatal-message prefix>  (for Fatal Python error fatals)
"""
import json, re, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPORTS = ROOT / "reports"
OUT = ROOT / "catalog" / "known_sites.tsv"

FRAME = re.compile(r'([A-Za-z_]\w+)@([\w./+-]+\.(?:c|h)):(\d+)')      # func@file:line
FILELINE = re.compile(r'([\w./+-]+\.(?:c|h)):(\d+)')                   # file:line
SITE = re.compile(r'(\S+\.(?:c|h))\s+(\S+).*?:(\d+)(?:-\d+)?$')        # "<file> <func..>:<line[-range]>"
# assertion line: "<file>:<line>: [ret] <func>[(args)]: Assertion <q>expr<q>" -- handles
# glibc backticks AND CPython double-quotes, and an optional (args) list.
ASSERT = re.compile(r"([\w./+-]+\.(?:c|h)):(\d+):.*?\b(\w+)\s*(?:\([^)]*\))?\s*:\s*Assertion[ `\"]+([^`'\"\n\t]*)")
ASSERT_NOFUNC = re.compile(r"([\w./+-]+\.(?:c|h)):(\d+):.*?Assertion[ `\"]+([^`'\"\n\t]*)")
FATAL = re.compile(r'Fatal Python error:\s*([^\n]+)')

# Non-discriminative "no exception pending" invariant asserts: they appear in many
# functions, so a FILE-scoped assert key (file:expr) collides when one file has two such
# bugs (e.g. specialize.c has specialize@364 = OOM-0011 AND unspecialize@378 = OOM-0025,
# both asserting !PyErr_Occurred()). Skip the assert key for these -- the func + line keys
# are the real discriminators. Discriminative asserts (data != NULL, gc_get_refs(op) >= 0,
# PyStackRef_BoolCheck(cond), ...) still get assert keys.
GENERIC_ASSERTS = {"!PyErr_Occurred()", "!_PyErr_Occurred(tstate)"}


def norm_file(f):
    return f.lstrip("./")


def collect():
    rows = set()  # (oom_id, kind, keytype, key)
    for meta in sorted(REPORTS.glob("*/meta.json")):
        d = json.loads(meta.read_text())
        oid, kind = d["id"], d.get("crash_kind", "?")
        sig = d.get("signature", {})
        frames = [sig.get("site_frame")] + list(sig.get("top_frames", []))
        # clean func@file:line frames from the signature
        for fr in filter(None, frames):
            m = FRAME.match(fr)
            if m:
                func, f, ln = m.group(1), norm_file(m.group(2)), m.group(3)
                rows.add((oid, kind, "func", f"{f}:{func}"))
                rows.add((oid, kind, "line", f"{f}:{ln}"))
        # func + line from the "<file> <func>:<line>" sites[] strings (note: file and
        # func are space-separated, so a plain file:line regex misses the func).
        for s in d.get("sites", []):
            m = SITE.match(s.strip())
            if m:
                f = norm_file(m.group(1))
                rows.add((oid, kind, "func", f"{f}:{m.group(2)}"))
                rows.add((oid, kind, "line", f"{f}:{m.group(3)}"))
            else:
                for fm in FILELINE.finditer(s):
                    rows.add((oid, kind, "line", f"{norm_file(fm.group(1))}:{fm.group(2)}"))
        # assertion expressions + fatal messages from the report's backtrace.txt.
        # assert keys are FILE-SCOPED (file:expr) so a common assertion like
        # `!PyErr_Occurred()` in a *different* file is not mistaken for this bug.
        bt = meta.parent / "backtrace.txt"
        if bt.exists():
            txt = bt.read_text()
            seen_assert_lines = set()
            for f, ln, func, expr in ASSERT.findall(txt):
                fn = norm_file(f)
                if expr.strip() not in GENERIC_ASSERTS:
                    rows.add((oid, kind, "assert", f"{fn}:{expr.strip()}"))
                rows.add((oid, kind, "func", f"{fn}:{func}"))
                rows.add((oid, kind, "line", f"{fn}:{ln}"))
                seen_assert_lines.add((fn, expr.strip()))
            for f, ln, expr in ASSERT_NOFUNC.findall(txt):  # catch lines w/o a parseable func
                fn = norm_file(f)
                if (fn, expr.strip()) not in seen_assert_lines:
                    if expr.strip() not in GENERIC_ASSERTS:
                        rows.add((oid, kind, "assert", f"{fn}:{expr.strip()}"))
                    rows.add((oid, kind, "line", f"{fn}:{ln}"))
            for f in FATAL.findall(txt):
                msg = f.strip()
                # skip non-discriminative wrappers (the real site is in the gdb frame,
                # not this message) so they don't absorb a genuinely-new assert bug.
                if msg.startswith(("_PyObject_AssertFailed", "_Py_NegativeRefcount")):
                    continue
                if msg and not msg.lower().startswith(("segmentation", "aborted")):
                    rows.add((oid, kind, "msg", msg[:60]))
    return rows


def main():
    rows = sorted(collect())
    OUT.parent.mkdir(exist_ok=True)
    with OUT.open("w") as fh:
        fh.write("# oom_id\tkind\tkeytype\tkey\n")
        for r in rows:
            fh.write("\t".join(r) + "\n")
    kinds = {}
    ids = set()
    for oid, kind, kt, _ in rows:
        ids.add(oid); kinds[kt] = kinds.get(kt, 0) + 1
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} keys for {len(ids)} bugs | by keytype: {kinds}")


if __name__ == "__main__":
    main()
