#!/usr/bin/env python3
"""Generate catalog/known_sites.tsv: a flat, read-only dedupe snapshot derived from the
canonical catalog (reports/*/meta.json + each report's backtrace.txt). Fuzzer instances
and the ingest tool load this instead of parsing every meta.json; it is regenerated by
the single writer (triage) whenever the catalog changes -- so there is never a shared
*mutable* catalog and thus no concurrent-write problem.

Row format (tab-separated):  <oom_id>\t<kind>\t<keytype>\t<key>
  keytype=func   key=<file>:<func>          (most stable across line drift)
  keytype=line   key=<file>:<line>          (exact; near-match handled by the matcher)
  keytype=assert key=<assertion expression> (discriminates same-func eval asserts)
  keytype=msg    key=<fatal-message prefix>  (for Fatal Python error fatals)
"""
import json, re, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPORTS = ROOT / "reports"
OUT = ROOT / "catalog" / "known_sites.tsv"

FRAME = re.compile(r'([A-Za-z_]\w+)@([\w./+-]+\.(?:c|h)):(\d+)')      # func@file:line
FILELINE = re.compile(r'([\w./+-]+\.(?:c|h)):(\d+)')                   # file:line
SITE = re.compile(r'(\S+\.(?:c|h))\s+(\S+).*?:(\d+)(?:-\d+)?$')        # "<file> <func..>:<line[-range]>"
# assertion line: "<file>:<line>: [ret] <func>[(args)]: Assertion <q>expr<q>" -- handles
# glibc backticks AND CPython double-quotes, and an optional (args) list.
ASSERT = re.compile(r"([\w./+-]+\.(?:c|h)):(\d+):.*?\b(\w+)\s*(?:\([^)]*\))?\s*:\s*Assertion[ `\"]+([^`'\"\n\t]*)")
ASSERT_NOFUNC = re.compile(r"([\w./+-]+\.(?:c|h)):(\d+):.*?Assertion[ `\"]+([^`'\"\n\t]*)")
FATAL = re.compile(r'Fatal Python error:\s*([^\n]+)')

# Non-discriminative "no exception pending" invariant asserts: they appear in many
# functions, so a FILE-scoped assert key (file:expr) collides when one file has two such
# bugs (e.g. specialize.c has specialize@364 = OOM-0011 AND unspecialize@378 = OOM-0025,
# both asserting !PyErr_Occurred()). Skip the assert key for these -- the func + line keys
# are the real discriminators. Discriminative asserts (data != NULL, gc_get_refs(op) >= 0,
# PyStackRef_BoolCheck(cond), ...) still get assert keys.
GENERIC_ASSERTS = {"!PyErr_Occurred()", "!_PyErr_Occurred(tstate)"}

# The negative-refcount / assert-failed DETECTOR. `_Py_NegativeRefcount` and
# `_PyObject_AssertFailed` *catch* the corruption; their own frames (Objects/object.c:275 /
# :3278) and the "negative ref count" assert appear in EVERY negrefcount abort, so emitting
# them as keys collides the whole family (OOM-0005 stackref, OOM-0019 pegen, OOM-0029
# dealloc-cascade all share object.c:_Py_NegativeRefcount + object.c:275 + that assert -- so a
# negrefcount crash matches them all and decide()'s sorted()[0] tiebreak picks the lowest id).
# They are detectors, not the defect: skip their func/line/assert keys; each bug keeps its own
# real site keys (the dealloc cascade, the pegen frames, PyStackRef_XCLOSE@pycore_stackref.h:726
# from its signature). Mirrors oom_dedup._BT_SKIP, which already drops these frames when
# resolving a live backtrace.
#
# The debug allocator's free-time check functions are detectors too: _PyMem_DebugCheckAddress /
# _PyMem_DebugRawFree / _PyMem_DebugFree *catch* a bad/double free (the "bad ID" fatal), but the
# real defect is the CALLER doing the bad free (e.g. free_threadstate for OOM-0020). Keying these
# generic frames lets OOM-0020 absorb any unrelated bad-free crash (the freed block always passes
# through the same allocator). Skip them so the keyed site is the caller; OOM-0020 still keys on
# free_threadstate + its specific "bad ID ... API ' '" message. Mirrors oom_dedup._BT_SKIP.
# `_Py_Dealloc` is the universal deallocation chokepoint (object.c:3319 dispatch; :3338 the
# "deallocator cleared the exception" fatal). It appears in EVERY dealloc crash, so keying it
# collides the whole dealloc family -- OOM-0003/0018/0024/0029 all share object.c:_Py_Dealloc +
# object.c:3319, and OOM-0007/0023 share :3338, so decide()'s sorted()[0] tiebreak silently
# mislabels e.g. a deque dealloc-clears-exc crash as OOM-0003. It is a detector frame, not the
# defect: each bug keeps its real site (code_dealloc, templateiter_dealloc, context_tp_dealloc,
# subtype_dealloc, ...) and the clears-exc family keeps its type-specific fatal msg. With the key
# gone, oom_dedup/ingest no longer match a crash to a bug via this generic frame.
GENERIC_DETECTOR_FUNCS = {"_Py_NegativeRefcount", "_PyObject_AssertFailed", "_Py_Dealloc",
                          "_PyMem_DebugCheckAddress", "_PyMem_DebugRawFree", "_PyMem_DebugFree"}

# Inlined refcount/atomic helper headers: Py_DECREF / Py_XDECREF / _Py_atomic_* expand here,
# so a frame in one of these files (e.g. refcount.h:520, the negrefcount-detecting Py_DECREF)
# is the generic macro body, not the bug -- it appears in every negrefcount abort and is never
# discriminative. Skip ALL keys for them, mirroring oom_dedup._BT_SKIP_FILE so the snapshot and
# the live-backtrace resolver agree on what counts as a real site.
DETECTOR_FILE = re.compile(r'(?:^|/)(?:refcount|pyatomic\w*|object)\.h$')


def norm_file(f):
    return f.lstrip("./")


def _skip_keys(file, func):
    """A frame whose func is a detector or whose file is an inlined macro header -> emit no keys."""
    return func in GENERIC_DETECTOR_FUNCS or bool(DETECTOR_FILE.search(norm_file(file)))


def _generic_assert(expr):
    """True if this assertion is non-discriminative across bugs (skip its file:expr key)."""
    e = expr.strip()
    return e in GENERIC_ASSERTS or "negative ref count" in e


def collect():
    rows = set()  # (oom_id, kind, keytype, key)
    for meta in sorted(REPORTS.glob("*/meta.json")):
        d = json.loads(meta.read_text())
        oid, kind = d["id"], d.get("crash_kind", "?")
        # msg_family: a substring catch-all for a whole bug FAMILY whose fatal differs only by
        # a variable token (e.g. OOM-0023's generic subtype_dealloc: "Deallocator of type 'X'
        # cleared the current exception" for any X). The matcher tries exact msg keys first
        # (longest wins -> Context->OOM-0007, deque->OOM-0039) and only falls back to msgfam, so
        # arbitrary new/fuzzer types (Evil, weird_*, _StoreTrueAction, ...) dedup here instead of
        # re-surfacing as oomNEW. Scoped to the exact suffix so the 'raised'/'overrode' invariant
        # variants (different defects) are NOT absorbed.
        for sub in d.get("msg_family", []):
            rows.add((oid, kind, "msgfam", sub))
        sig = d.get("signature", {})
        frames = [sig.get("site_frame")] + list(sig.get("top_frames", []))
        # clean func@file:line frames from the signature
        for fr in filter(None, frames):
            m = FRAME.match(fr)
            if m:
                func, f, ln = m.group(1), norm_file(m.group(2)), m.group(3)
                if _skip_keys(f, func):              # detector func / inlined-macro header
                    continue
                rows.add((oid, kind, "func", f"{f}:{func}"))
                rows.add((oid, kind, "line", f"{f}:{ln}"))
        # func + line from the "<file> <func>:<line>" sites[] strings (note: file and
        # func are space-separated, so a plain file:line regex misses the func).
        for s in d.get("sites", []):
            m = SITE.match(s.strip())
            if m:
                f = norm_file(m.group(1))
                if _skip_keys(f, m.group(2)):        # detector func / inlined-macro header
                    continue
                rows.add((oid, kind, "func", f"{f}:{m.group(2)}"))
                rows.add((oid, kind, "line", f"{f}:{m.group(3)}"))
            elif not any(g in s for g in GENERIC_DETECTOR_FUNCS):  # not a detector site string
                for fm in FILELINE.finditer(s):
                    f = norm_file(fm.group(1))
                    if DETECTOR_FILE.search(f):      # inlined-macro header line -> not a site
                        continue
                    rows.add((oid, kind, "line", f"{f}:{fm.group(2)}"))
        # assertion expressions + fatal messages from the report's backtrace.txt.
        # assert keys are FILE-SCOPED (file:expr) so a common assertion like
        # `!PyErr_Occurred()` in a *different* file is not mistaken for this bug.
        bt = meta.parent / "backtrace.txt"
        if bt.exists():
            txt = bt.read_text()
            seen_assert_lines = set()
            for f, ln, func, expr in ASSERT.findall(txt):
                fn = norm_file(f)
                seen_assert_lines.add((fn, expr.strip()))
                if _skip_keys(fn, func):             # detector line -> skip all of its keys
                    continue
                if not _generic_assert(expr):
                    rows.add((oid, kind, "assert", f"{fn}:{expr.strip()}"))
                rows.add((oid, kind, "func", f"{fn}:{func}"))
                rows.add((oid, kind, "line", f"{fn}:{ln}"))
            for f, ln, expr in ASSERT_NOFUNC.findall(txt):  # catch lines w/o a parseable func
                fn = norm_file(f)
                if (fn, expr.strip()) not in seen_assert_lines and not DETECTOR_FILE.search(fn):
                    if not _generic_assert(expr):
                        rows.add((oid, kind, "assert", f"{fn}:{expr.strip()}"))
                    rows.add((oid, kind, "line", f"{fn}:{ln}"))
            for f in FATAL.findall(txt):
                msg = f.strip()
                # skip non-discriminative wrappers (the real site is in the gdb frame,
                # not this message) so they don't absorb a genuinely-new assert bug.
                if msg.startswith(("_PyObject_AssertFailed", "_Py_NegativeRefcount")):
                    continue
                if msg and not msg.lower().startswith(("segmentation", "aborted")):
                    rows.add((oid, kind, "msg", msg[:60]))
    return rows


def main():
    rows = sorted(collect())
    OUT.parent.mkdir(exist_ok=True)
    with OUT.open("w") as fh:
        fh.write("# oom_id\tkind\tkeytype\tkey\n")
        for r in rows:
            fh.write("\t".join(r) + "\n")
    kinds = {}
    ids = set()
    for oid, kind, kt, _ in rows:
        ids.add(oid); kinds[kt] = kinds.get(kt, 0) + 1
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} keys for {len(ids)} bugs | by keytype: {kinds}")


if __name__ == "__main__":
    main()
